export const UncrustifyTemplate = {
  sp_inside_oc_at_sel_parens: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_version_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_func_class_def: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_braces_no_class: [null, 'true', 'false'],
  indent_paren_after_func_call: [null, 'true', 'false'],
  align_keep_extra_space: [null, 'true', 'false'],
  sp_after_operator_sym_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_enum_colon: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_annotation: [null, 'ignore', 'add', 'remove', 'force'],
  indent_single_after_return: [null, 'true', 'false'],
  sp_before_type_brace_init_lst_close: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_after_oc_property: [null, 'ignore', 'add', 'remove', 'force'],
  nl_max_blank_in_func: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_incdec: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_width: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_after_byref_func: [null, 'ignore', 'add', 'remove', 'force'],
  sp_finally_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_send_oc_colon: [null, 'ignore', 'add', 'remove', 'force'],
  mod_sort_oc_property_reference_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  sp_sign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_return_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_sparen: [null, 'ignore', 'add', 'remove', 'force'],
  pos_class_comma: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  pp_ignore_define_body: [null, 'true', 'false'],
  nl_assign_brace: [null, 'ignore', 'add', 'remove', 'force'],
  pos_constr_colon: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  sp_before_ptr_star_func: [null, 'ignore', 'add', 'remove', 'force'],
  nl_type_brace_init_lst: [null, 'ignore', 'add', 'remove', 'force'],
  indent_case_shift: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_func_params_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_d_array_colon: [null, 'ignore', 'add', 'remove', 'force'],
  nl_type_brace_init_lst_close: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_typedef_blk_in: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_inv: [null, 'ignore', 'add', 'remove', 'force'],
  pos_bool: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  pp_indent_if: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  cmt_multi_first_len_minimum: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_before_return: [null, 'true', 'false'],
  sp_extern_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_compare: [null, 'ignore', 'add', 'remove', 'force'],
  nl_ds_struct_enum_cmt: [null, 'true', 'false'],
  nl_scope_brace: [null, 'ignore', 'add', 'remove', 'force'],
  pos_comma: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  indent_constr_colon: [null, 'true', 'false'],
  cmt_insert_before_ctor_dtor: [null, 'true', 'false'],
  mod_full_brace_if: [null, 'ignore', 'add', 'remove', 'force'],
  mod_sort_oc_property_class_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  sp_paren_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_angle: [null, 'ignore', 'add', 'remove', 'force'],
  sp_func_call_paren_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_enum_assign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_braces: [null, 'ignore', 'add', 'remove', 'force'],
  nl_end_of_file: [null, 'ignore', 'add', 'remove', 'force'],
  indent_col1_comment: [null, 'true', 'false'],
  sp_not: [null, 'ignore', 'add', 'remove', 'force'],
  indent_member_single: [null, 'true', 'false'],
  indent_continue: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_split_if_one_liner: [null, 'true', 'false'],
  nl_func_call_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_super_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_switch: [null, 'ignore', 'add', 'remove', 'force'],
  sp_assign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_mdatype_commas: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  align_typedef_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  pp_indent_func_def: [null, 'true', 'false'],
  pp_indent_at_level: [null, 'true', 'false'],
  sp_before_constr_colon: [null, 'ignore', 'add', 'remove', 'force'],
  tok_split_gte: [null, 'true', 'false'],
  cmt_star_cont: [null, 'true', 'false'],
  nl_enum_own_lines: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_switch: [null, 'ignore', 'add', 'remove', 'force'],
  indent_class_colon: [null, 'true', 'false'],
  indent_ignore_asm_block: [null, 'true', 'false'],
  nl_after_brace_close: [null, 'true', 'false'],
  indent_var_def_blk: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_try_brace: [null, 'ignore', 'add', 'remove', 'force'],
  string_escape_char2: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_decl_empty: [null, 'ignore', 'add', 'remove', 'force'],
  align_number_right: [null, 'true', 'false'],
  nl_before_for: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_for_colon: [null, 'ignore', 'add', 'remove', 'force'],
  mod_add_long_ifdef_endif_comment: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_fparen_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_getset_leave_one_liners: [null, 'true', 'false'],
  nl_after_brace_open_cmt: [null, 'true', 'false'],
  nl_struct_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_label_colon: [null, 'true', 'false'],
  sp_func_class_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_func_proto_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_constr_colon: [null, 'ignore', 'add', 'remove', 'force'],
  mod_full_brace_nl: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_after_oc_dict_colon: [null, 'ignore', 'add', 'remove', 'force'],
  nl_class_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_while: [null, 'ignore', 'add', 'remove', 'force'],
  sp_else_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_angle_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_between_annotation: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_func_params_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_tsquare_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_func_call_user_paren_paren: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_ds_struct_enum_close_brace: [null, 'true', 'false'],
  sp_cond_colon: [null, 'ignore', 'add', 'remove', 'force'],
  indent_paren_close: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_using_brace: [null, 'ignore', 'add', 'remove', 'force'],
  utf8_bom: [null, 'ignore', 'add', 'remove', 'force'],
  nl_multi_line_define: [null, 'true', 'false'],
  nl_after_func_proto: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_while_brace: [null, 'ignore', 'add', 'remove', 'force'],
  //  indent_with_tabs: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_with_tabs: [0],
  indent_ternary_operator: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_var_def_blk_in: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_num_before_tr_emb_cmt: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_decl_start_single: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_func_def_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_star_style: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_deref: [null, 'ignore', 'add', 'remove', 'force'],
  nl_fdef_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_operator_sym: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_call_end_multi_line: [null, 'true', 'false'],
  sp_after_oc_at_sel_parens: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_assign_square: [null, 'ignore', 'add', 'remove', 'force'],
  sp_getset_brace: [null, 'ignore', 'add', 'remove', 'force'],
  indent_single_newlines: [null, 'true', 'false'],
  nl_brace_finally: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_newop_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_extern: [null, 'true', 'false'],
  indent_align_assign: [null, 'true', 'false'],
  sp_after_oc_colon: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_struct: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_bool_paren: [null, 'true', 'false'],
  indent_namespace: [null, 'true', 'false'],
  align_left_shift: [null, 'true', 'false'],
  mod_remove_extra_semicolon: [null, 'true', 'false'],
  cmt_convert_tab_to_spaces: [null, 'true', 'false'],
  indent_oc_block_msg: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_before_func_body_def: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  mod_paren_on_return: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cmt_cpp_qttr: [null, 'true', 'false'],
  nl_after_vbrace_open_empty: [null, 'true', 'false'],
  sp_after_ptr_star: [null, 'ignore', 'add', 'remove', 'force'],
  nl_while_leave_one_liners: [null, 'true', 'false'],
  indent_relative_single_line_comments: [null, 'true', 'false'],
  align_struct_init_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_before_pp_stringify: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_class_param: [null, 'true', 'false'],
  pp_region_indent_code: [null, 'true', 'false'],
  align_typedef_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_decl_args: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_square: [null, 'ignore', 'add', 'remove', 'force'],
  sp_square_fparen: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cond_colon_before: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_insert_class_header: null,
  sp_inside_type_brace_init_lst: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_func_decl_end_single: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_insert_file_footer: null,
  indent_template_param: [null, 'true', 'false'],
  indent_func_def_param: [null, 'true', 'false'],
  pp_space_count: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_oc_implementation_brace: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_fparen_brace_initializer: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_else_brace: [null, 'ignore', 'add', 'remove', 'force'],
  align_enum_equ_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_paren_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_new: [null, 'ignore', 'add', 'remove', 'force'],
  code_width: [null, 70, 72, 74, 76, 78, 80, 84, 88, 89, 90, 98],
  indent_semicolon_for_paren: [null, 'true', 'false'],
  indent_xml_string: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_assign_leave_one_liners: [null, 'true', 'false'],
  nl_cpp_lambda_leave_one_liners: [null, 'true', 'false'],
  align_var_def_amp_style: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_var_def_blk_end: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_oc_block: [null, 'true', 'false'],
  use_options_overriding_for_qt_macros: [null, 'true', 'false'],
  nl_after_brace_open: [null, 'true', 'false'],
  sp_func_def_paren: [null, 'ignore', 'add', 'remove', 'force'],
  mod_full_brace_using: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_decl_end: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_square_oc_array: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_brace_brace: [null, 'ignore', 'add', 'remove', 'force'],
  pos_enum_comma: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  nl_after_multiline_comment: [null, 'true', 'false'],
  nl_after_class: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_for: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_newop_paren_close: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  align_single_line_brace: [null, 'true', 'false'],
  sp_angle_paren_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_addr: [null, 'ignore', 'add', 'remove', 'force'],
  indent_access_spec_body: [null, 'true', 'false'],
  mod_sort_using: [null, 'true', 'false'],
  sp_before_comma: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_leave_one_liners: [null, 'true', 'false'],
  nl_class_leave_one_liners: [null, 'true', 'false'],
  sp_after_oc_msg_receiver: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_squeeze_paren_close: [null, 'true', 'false'],
  sp_angle_word: [null, 'ignore', 'add', 'remove', 'force'],
  eat_blanks_after_open_brace: [null, 'true', 'false'],
  sp_after_semi_for: [null, 'ignore', 'add', 'remove', 'force'],
  sp_special_semi: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_semi_for_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_oc_block_brace: [null, 'ignore', 'add', 'remove', 'force'],
  indent_align_string: [null, 'true', 'false'],
  align_on_tabstop: [null, 'true', 'false'],
  sp_after_assign: [null, 'ignore', 'add', 'remove', 'force'],
  nl_template_class: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_var_def_blk: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_def_start: [null, 'ignore', 'add', 'remove', 'force'],
  align_func_proto_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_elseif_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_class: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_call_start_multi_line: [null, 'true', 'false'],
  align_enum_equ_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_token_after_brace: [null, 'true', 'false'],
  nl_cpp_ldef_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_assign: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_semicolon: [null, 'true', 'false'],
  indent_cs_delegate_brace: [null, 'true', 'false'],
  sp_after_newop_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_ptr_star_qualifier: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_off_after_return_new: [null, 'true', 'false'],
  align_var_class_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_getset_brace: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_indent_multi: [null, 'true', 'false'],
  sp_after_noexcept: [null, 'ignore', 'add', 'remove', 'force'],
  sp_member: [null, 'ignore', 'add', 'remove', 'force'],
  sp_brace_finally: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_byref: [null, 'ignore', 'add', 'remove', 'force'],
  indent_var_def_cont: [null, 'true', 'false'],
  nl_constr_init_args: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_square: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_dc: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_def_force_col1: [null, 'true', 'false'],
  sp_cparen_oparen: [null, 'ignore', 'add', 'remove', 'force'],
  sp_angle_colon: [null, 'ignore', 'add', 'remove', 'force'],
  sp_catch_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_cpp_lambda_body: [null, 'true', 'false'],
  nl_else_if: [null, 'ignore', 'add', 'remove', 'force'],
  sp_defined_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_oc_block_msg_from_caret: [null, 'true', 'false'],
  nl_return_expr: [null, 'ignore', 'add', 'remove', 'force'],
  sp_type_brace_init_lst: [null, 'ignore', 'add', 'remove', 'force'],
  mod_sort_oc_property_getter_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  pp_indent_region: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_func_proto_type_name: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_call_param: [null, 'true', 'false'],
  sp_before_class_colon: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_def_args_multi_line: [null, 'true', 'false'],
  cmt_sp_after_star_cont: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  cmt_multi_check_last: [null, 'true', 'false'],
  align_oc_msg_colon_first: [null, 'true', 'false'],
  sp_bool: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_class_identifier: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_switch_pp: [null, 'true', 'false'],
  sp_inside_fparens: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_colon: [null, 'true', 'false'],
  sp_endif_cmt: [null, 'ignore', 'add', 'remove', 'force'],
  sp_skip_vbrace_tokens: [null, 'true', 'false'],
  nl_if_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_typedef_blk_end: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_case_colon_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_unnamed_ptr_star: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_brace_while: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_byref_func: [null, 'ignore', 'add', 'remove', 'force'],
  disable_processing_cmt: null,
  cmt_cpp_nl_start: [null, 'true', 'false'],
  ls_for_split_full: [null, 'true', 'false'],
  sp_after_type: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_synchronized: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_return: [null, 'true', 'false'],
  mod_full_brace_while: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_oc_return_type: [null, 'ignore', 'add', 'remove', 'force'],
  nl_finally_brace: [null, 'ignore', 'add', 'remove', 'force'],
  mod_full_brace_if_chain: [null, 'true', 'false'],
  //  nl_max: [ null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_vbrace_close: [null, 'true', 'false'],
  indent_paren_nl: [null, 'true', 'false'],
  sp_sizeof_paren: [null, 'ignore', 'add', 'remove', 'force'],
  mod_add_long_function_closebrace_comment: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  sp_after_send_oc_colon: [null, 'ignore', 'add', 'remove', 'force'],
  sp_case_label: [null, 'ignore', 'add', 'remove', 'force'],
  align_single_line_brace_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_synchronized_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_def_end_multi_line: [null, 'true', 'false'],
  sp_cond_question: [null, 'ignore', 'add', 'remove', 'force'],
  enable_processing_cmt: null,
  align_right_cmt_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_squeeze_ifdef: [null, 'true', 'false'],
  nl_unittest_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_try_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_semi: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_struct_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_oc_block_msg_xcode_style: [null, 'true', 'false'],
  align_typedef_func: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_before_case: [null, 'true', 'false'],
  indent_cpp_lambda_only_once: [null, 'true', 'false'],
  mod_full_brace_nl_block_rem_mlcond: [null, 'true', 'false'],
  pp_indent_extern: [null, 'true', 'false'],
  sp_after_invariant_paren: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_namespace_level: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_right_cmt_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_same_func_call_params: [null, 'true', 'false'],
  indent_switch_case: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_call_paren_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_namespace_single_indent: [null, 'true', 'false'],
  nl_func_def_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cpp_before_struct_binding: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_after_if: [null, 'ignore', 'add', 'remove', 'force'],
  pos_class_colon: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  nl_before_cpp_comment: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_angle_shift: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_constr_colon: [null, 'ignore', 'add', 'remove', 'force'],
  ls_code_width: [null, 'true', 'false'],
  indent_paren_open_brace: [null, 'true', 'false'],
  sp_before_ptr_star: [null, 'ignore', 'add', 'remove', 'force'],
  nl_split_for_one_liner: [null, 'true', 'false'],
  indent_paren_after_func_def: [null, 'true', 'false'],
  sp_pp_concat: [null, 'ignore', 'add', 'remove', 'force'],
  indent_access_spec: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_type_brace_init_lst_open: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_oc_msg_prioritize_first_colon: [null, 'true', 'false'],
  ls_func_split_full: [null, 'true', 'false'],
  sp_cond_colon_after: [null, 'ignore', 'add', 'remove', 'force'],
  nl_typedef_blk_start: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_leave_one_liners: [null, 'true', 'false'],
  nl_namespace_two_to_one_liner: [null, 'true', 'false'],
  sp_after_cast: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_c_nl_start: [null, 'true', 'false'],
  pp_space: [null, 'ignore', 'add', 'remove', 'force'],
  sp_func_call_user_paren: [null, 'ignore', 'add', 'remove', 'force'],
  pp_define_at_level: [null, 'true', 'false'],
  sp_after_mdatype_commas: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_ellipsis: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_throw: [null, 'ignore', 'add', 'remove', 'force'],
  sp_permit_cpp11_shift: [null, 'true', 'false'],
  cmt_insert_func_header: null,
  align_mix_var_proto: [null, 'true', 'false'],
  nl_func_decl_start_multi_line: [null, 'true', 'false'],
  indent_label: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  pp_if_indent_code: [null, 'true', 'false'],
  sp_macro_func: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_attribute: [null, 'true', 'false'],
  sp_cond_question_after: [null, 'ignore', 'add', 'remove', 'force'],
  pos_constr_comma: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  nl_after_func_proto_group: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_before_sparen: [null, 'ignore', 'add', 'remove', 'force'],
  indent_param: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_do: [null, 'ignore', 'add', 'remove', 'force'],
  indent_else_if: [null, 'true', 'false'],
  align_asm_colon: [null, 'true', 'false'],
  align_var_def_inline: [null, 'true', 'false'],
  sp_annotation_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_paren_comma: [null, 'ignore', 'add', 'remove', 'force'],
  sp_enum_paren: [null, 'ignore', 'add', 'remove', 'force'],
  mod_case_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_pp_stringify: [null, 'ignore', 'add', 'remove', 'force'],
  indent_oc_block_msg_from_keyword: [null, 'true', 'false'],
  indent_class_on_colon: [null, 'true', 'false'],
  nl_before_access_spec: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_before_unnamed_byref: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_oc_type: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_class: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_insert_file_header: null,
  newlines: [null, 'auto', 'lf', 'crlf', 'cr'],
  sp_after_oc_at_sel: [null, 'ignore', 'add', 'remove', 'force'],
  sp_type_func: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  cmt_c_group: [null, 'true', 'false'],
  nl_if_leave_one_liners: [null, 'true', 'false'],
  indent_brace_parent: [null, 'true', 'false'],
  mod_add_long_ifdef_else_comment: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_enum_after_assign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_brace_typedef: [null, 'ignore', 'add', 'remove', 'force'],
  align_pp_define_together: [null, 'true', 'false'],
  sp_before_semi_for: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_colon_type: [null, 'ignore', 'add', 'remove', 'force'],
  sp_oc_brace_catch: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_def_start_single: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  align_nl_cont: [null, 'true', 'false'],
  indent_braces_no_struct: [null, 'true', 'false'],
  sp_after_byref: [null, 'ignore', 'add', 'remove', 'force'],
  sp_template_angle: [null, 'ignore', 'add', 'remove', 'force'],
  nl_comment_func_def: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_sing_line_comments: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_call_args_multi_line: [null, 'true', 'false'],
  mod_full_brace_function: [null, 'ignore', 'add', 'remove', 'force'],
  nl_create_while_one_liner: [null, 'true', 'false'],
  sp_oc_catch_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_func_body: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_scope_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_struct_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_comma_paren: [null, 'true', 'false'],
  use_indent_func_call_param: [null, 'true', 'false'],
  sp_before_angle: [null, 'ignore', 'add', 'remove', 'force'],
  mod_sort_include: [null, 'true', 'false'],
  sp_inside_braces_oc_dict: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_preserve_sql: [null, 'true', 'false'],
  sp_fparen_dbrace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_split_while_one_liner: [null, 'true', 'false'],
  nl_create_if_one_liner: [null, 'true', 'false'],
  mod_move_case_break: [null, 'true', 'false'],
  mod_full_paren_if_bool: [null, 'true', 'false'],
  align_typedef_star_style: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_brace_else: [null, 'ignore', 'add', 'remove', 'force'],
  nl_oc_interface_brace: [null, 'ignore', 'add', 'remove', 'force'],
  indent_columns: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_between_get_set: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  force_tab_after_define: [null, 'true', 'false'],
  sp_range: [null, 'ignore', 'add', 'remove', 'force'],
  nl_around_cs_property: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  pp_indent_case: [null, 'true', 'false'],
  nl_start_of_file_min: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_do_brace: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_class_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_func_class_proto_group: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_property_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_func_def_paren_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_ptr_block_caret: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_collapse_empty_body: [null, 'true', 'false'],
  sp_word_brace_ns: [null, 'ignore', 'add', 'remove', 'force'],
  mod_add_long_namespace_closebrace_comment: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_after_square_assign: [null, 'ignore', 'add', 'remove', 'force'],
  nl_var_def_blk_start: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_right_cmt_at_col: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_ptr_star_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_vbrace_open: [null, 'true', 'false'],
  align_keep_tabs: [null, 'true', 'false'],
  nl_namespace_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_tparen: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_class_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_brace: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  pp_indent: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_tparen_close: [null, 'ignore', 'add', 'remove', 'force'],
  nl_switch_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_invariant_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_call_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_throw: [null, 'ignore', 'add', 'remove', 'force'],
  sp_arith_additive: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_func_class_proto: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  cmt_sp_before_star_cont: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_after_semi_for_empty: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cond_ternary_short: [null, 'ignore', 'add', 'remove', 'force'],
  nl_brace_catch: [null, 'ignore', 'add', 'remove', 'force'],
  align_func_params: [null, 'true', 'false'],
  mod_sort_import: [null, 'true', 'false'],
  align_oc_msg_spec_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_func_body_class: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_synchronized: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_oc_block_caret: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_before_oc_dict_colon: [null, 'ignore', 'add', 'remove', 'force'],
  align_on_operator: [null, 'true', 'false'],
  mod_full_brace_for: [null, 'ignore', 'add', 'remove', 'force'],
  pos_compare: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  nl_after_func_class_proto: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_ctor_init_leading: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_var_def_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  mod_sort_oc_property_nullability_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  nl_class_colon: [null, 'ignore', 'add', 'remove', 'force'],
  sp_oc_catch_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_braces_no_func: [null, 'true', 'false'],
  nl_func_decl_args_multi_line: [null, 'true', 'false'],
  sp_catch_brace: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_insert_before_inlines: [null, 'true', 'false'],
  sp_func_call_user_inside_fparen: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_assign_default: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cond_question_before: [null, 'ignore', 'add', 'remove', 'force'],
  indent_square_nl: [null, 'true', 'false'],
  sp_func_proto_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_between_mdatype_commas: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_sparen_brace: [null, 'ignore', 'add', 'remove', 'force'],
  align_oc_decl_colon: [null, 'true', 'false'],
  sp_macro: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_oc_scope: [null, 'ignore', 'add', 'remove', 'force'],
  sp_version_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_assign_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_cs_property_leave_one_liners: [null, 'true', 'false'],
  sp_before_case_colon: [null, 'ignore', 'add', 'remove', 'force'],
  sp_attribute_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_for_brace: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_throw: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_squeeze_ifdef_top_level: [null, 'true', 'false'],
  nl_create_for_one_liner: [null, 'true', 'false'],
  sp_func_call_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cmt_cpp_doxygen: [null, 'true', 'false'],
  sp_inside_paren_cast: [null, 'ignore', 'add', 'remove', 'force'],
  use_indent_continue_only_once: [null, 'true', 'false'],
  mod_sort_oc_property_setter_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  indent_class: [null, 'true', 'false'],
  mod_add_long_class_closebrace_comment: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  mod_sort_oc_properties: [null, 'true', 'false'],
  sp_after_operator: [null, 'ignore', 'add', 'remove', 'force'],
  nl_after_func_body_one_liner: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  include_category_1: null,
  sp_after_semi: [null, 'ignore', 'add', 'remove', 'force'],
  sp_throw_paren: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_newop_paren_open: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_inside_sparen_open: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_braces_struct: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_reflow_mode: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  mod_sort_oc_property_readwrite_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  cmt_insert_before_preproc: [null, 'true', 'false'],
  sp_brace_else: [null, 'ignore', 'add', 'remove', 'force'],
  indent_case_brace: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  align_typedef_amp_style: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_using_block: [null, 'true', 'false'],
  nl_after_case: [null, 'true', 'false'],
  pos_assign: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  sp_before_tr_emb_cmt: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_func_body_proto: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  string_escape_char: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  indent_func_param_double: [null, 'true', 'false'],
  nl_func_def_paren_empty: [null, 'ignore', 'add', 'remove', 'force'],
  nl_multi_line_cond: [null, 'true', 'false'],
  sp_inside_fparen: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_cpp_nl_end: [null, 'true', 'false'],
  sp_inside_sparen_close: [null, 'ignore', 'add', 'remove', 'force'],
  nl_oc_msg_args: [null, 'true', 'false'],
  sp_cpp_lambda_assign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_cpp_lambda_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_type_name: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_c_nl_end: [null, 'true', 'false'],
  warn_level_tabs_found_in_verbatim_string_literals: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  pos_conditional: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  sp_cpp_cast_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_namespace_limit: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_fcall_brace: [null, 'ignore', 'add', 'remove', 'force'],
  pos_arith: [
    null,
    'ignore',
    'join',
    'lead',
    'lead_break',
    'lead_force',
    'trail',
    'trail_break',
    'trail_force',
  ],
  sp_word_brace: [null, 'ignore', 'add', 'remove', 'force'],
  nl_catch_brace: [null, 'ignore', 'add', 'remove', 'force'],
  eat_blanks_before_close_brace: [null, 'true', 'false'],
  nl_brace_square: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_def_start_multi_line: [null, 'true', 'false'],
  indent_align_paren: [null, 'true', 'false'],
  indent_member: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  utf8_byte: [null, 'true', 'false'],
  sp_enum_before_assign: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_paren: [null, 'ignore', 'add', 'remove', 'force'],
  indent_oc_block_msg_from_brace: [null, 'true', 'false'],
  nl_end_of_file_min: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_between_new_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_define_macro: [null, 'true', 'false'],
  mod_add_long_switch_closebrace_comment: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  indent_func_proto_param: [null, 'true', 'false'],
  sp_brace_catch: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_do: [null, 'ignore', 'add', 'remove', 'force'],
  include_category_0: null,
  align_right_cmt_mix: [null, 'true', 'false'],
  sp_before_dc: [null, 'ignore', 'add', 'remove', 'force'],
  cmt_insert_oc_msg_header: null,
  sp_inside_braces_empty: [null, 'ignore', 'add', 'remove', 'force'],
  indent_min_vbrace_open: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_func_type_name_class: [null, 'ignore', 'add', 'remove', 'force'],
  sp_balance_nested_parens: [null, 'true', 'false'],
  nl_func_decl_start: [null, 'ignore', 'add', 'remove', 'force'],
  nl_remove_extra_newlines: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_before_block_comment: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_after_ptr_star_func: [null, 'ignore', 'add', 'remove', 'force'],
  //  align_with_tabs: [null, 'true', 'false'],
  align_with_tabs: [null, 'false'],
  enable_digraphs: [null, 'true', 'false'],
  nl_start_of_file: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_nl_cont: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_class_scope: [null, 'ignore', 'add', 'remove', 'force'],
  nl_enum_identifier_colon: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_before_if: [null, 'ignore', 'add', 'remove', 'force'],
  include_category_2: null,
  indent_cs_delegate_body: [null, 'true', 'false'],
  pp_indent_brace: [null, 'true', 'false'],
  mod_pawn_semicolon: [null, 'true', 'false'],
  sp_between_ptr_star: [null, 'ignore', 'add', 'remove', 'force'],
  nl_before_c_comment: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_after_try_catch_finally: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_pp_define_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_func_proto_paren_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  mod_full_brace_if_chain_only: [null, 'true', 'false'],
  pp_indent_count: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  string_replace_tab_chars: [null, 'true', 'false'],
  sp_inside_braces_enum: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_def_end: [null, 'ignore', 'add', 'remove', 'force'],
  indent_first_for_expr: [null, 'true', 'false'],
  nl_union_brace: [null, 'ignore', 'add', 'remove', 'force'],
  mod_sort_oc_property_thread_safe_weight: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  sp_after_oc_block_caret: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_colon_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_assign_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_cmt_cpp_start: [null, 'ignore', 'add', 'remove', 'force'],
  indent_shift: [null, 'true', 'false'],
  nl_func_def_end_single: [null, 'ignore', 'add', 'remove', 'force'],
  align_single_line_func: [null, 'true', 'false'],
  nl_before_while: [null, 'ignore', 'add', 'remove', 'force'],
  indent_oc_msg_colon: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  cmt_cpp_to_c: [null, 'true', 'false'],
  indent_first_bool_expr: [null, 'true', 'false'],
  nl_class_init_args: [null, 'ignore', 'add', 'remove', 'force'],
  mod_full_brace_do: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_struct_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  align_pp_define_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_oc_msg_leave_one_liner: [null, 'true', 'false'],
  nl_after_access_spec: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_arith: [null, 'ignore', 'add', 'remove', 'force'],
  sp_inside_sparen: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_scope_name: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_ctor_var_param: [null, 'true', 'false'],
  sp_this_paren: [null, 'ignore', 'add', 'remove', 'force'],
  nl_func_decl_end_multi_line: [null, 'true', 'false'],
  sp_after_type_brace_init_lst_open: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_oc_brace_catch: [null, 'ignore', 'add', 'remove', 'force'],
  indent_cmt_with_tabs: [null, 'true', 'false'],
  nl_before_if_closing_paren: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  nl_brace_fparen: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_comma: [null, 'ignore', 'add', 'remove', 'force'],
  indent_paren_after_func_decl: [null, 'true', 'false'],
  mod_remove_empty_return: [null, 'true', 'false'],
  sp_before_squares: [null, 'ignore', 'add', 'remove', 'force'],
  nl_oc_catch_brace: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_oc_synchronized: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  indent_ctor_init: [
    null,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  sp_paren_paren: [null, 'ignore', 'add', 'remove', 'force'],
  align_func_params_gap: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_create_func_def_one_liner: [null, 'true', 'false'],
  indent_oc_block_msg_from_colon: [null, 'true', 'false'],
  nl_func_def_args: [null, 'ignore', 'add', 'remove', 'force'],
  sp_after_tag: [null, 'ignore', 'add', 'remove', 'force'],
  sp_before_template_paren: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  sp_before_oc_colon: [null, 'ignore', 'add', 'remove', 'force'],
  align_var_def_thresh: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  cmt_cpp_group: [null, 'true', 'false'],
  indent_braces: [null, 'true', 'false'],
  indent_vbrace_open_on_tabstop: [null, 'true', 'false'],
  sp_after_for_colon: [null, 'ignore', 'add', 'remove', 'force'],
  align_oc_msg_colon_span: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  nl_brace_struct_var: [null, 'ignore', 'add', 'remove', 'force'],
  utf8_force: [null, 'true', 'false'],
  sp_inside_angle: [null, 'ignore', 'add', 'remove', 'force'],
  nl_paren_dbrace_open: [null, 'ignore', 'add', 'remove', 'force'],
  indent_func_const: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  output_tab_size: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_after_class_colon: [null, 'ignore', 'add', 'remove', 'force'],
  sp_func_class_paren_empty: [
    null,
    'ignore',
    'add',
    'remove',
    'force',
  ],
  input_tab_size: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
};

export const UncrustifyDefaults = {
  nl_func_def_args_multi_line: 'false',
  sp_arith_additive: 'ignore',
  sp_fparen_brace: 'ignore',
  indent_oc_block: 'false',
  nl_after_semicolon: 'false',
  nl_namespace_brace: 'ignore',
  nl_typedef_blk_in: '0',
  nl_unittest_brace: 'ignore',
  pos_class_comma: 'ignore',
  nl_squeeze_paren_close: 'false',
  nl_for_brace: 'ignore',
  sp_after_oc_msg_receiver: 'ignore',
  sp_after_noexcept: 'ignore',
  align_var_class_thresh: '0',
  nl_before_cpp_comment: '0',
  indent_braces_no_func: 'false',
  sp_endif_cmt: 'ignore',
  mod_full_brace_using: 'ignore',
  sp_before_for_colon: 'ignore',
  sp_before_type_brace_init_lst_close: 'ignore',
  nl_version_brace: 'ignore',
  cmt_cpp_nl_start: 'false',
  indent_cs_delegate_brace: 'false',
  sp_before_ptr_star_func: 'ignore',
  indent_oc_block_msg_from_brace: 'false',
  nl_oc_implementation_brace: 'ignore',
  sp_extern_paren: 'ignore',
  nl_oc_catch_brace: 'ignore',
  align_typedef_star_style: '0',
  nl_after_for: 'ignore',
  sp_type_brace_init_lst: 'ignore',
  sp_before_class_colon: 'ignore',
  sp_after_oc_colon: 'ignore',
  nl_after_func_proto_group: '0',
  nl_case_colon_brace: 'ignore',
  nl_template_class: 'ignore',
  mod_sort_import: 'false',
  sp_assign: 'ignore',
  indent_cmt_with_tabs: 'false',
  sp_func_call_user_paren_paren: 'ignore',
  nl_scope_brace: 'ignore',
  nl_class_init_args: 'ignore',
  nl_after_if: 'ignore',
  cmt_sp_before_star_cont: '0',
  indent_oc_msg_colon: '0',
  align_func_params_thresh: '0',
  cmt_width: '0',
  align_right_cmt_gap: '0',
  align_var_class_span: '0',
  nl_type_brace_init_lst: 'ignore',
  nl_func_scope_name: 'ignore',
  nl_after_square_assign: 'ignore',
  nl_oc_interface_brace: 'ignore',
  sp_oc_catch_brace: 'ignore',
  align_assign_thresh: '0',
  nl_ds_struct_enum_close_brace: 'false',
  pp_space_count: '0',
  align_right_cmt_span: '0',
  indent_token_after_brace: 'true',
  align_var_class_gap: '0',
  sp_sign: 'remove',
  nl_func_decl_end: 'ignore',
  nl_enum_class: 'ignore',
  nl_func_decl_start: 'ignore',
  utf8_force: 'false',
  align_oc_msg_spec_span: '0',
  sp_paren_paren: 'ignore',
  indent_align_string: 'false',
  nl_func_decl_empty: 'ignore',
  indent_namespace_level: '0',
  nl_getset_leave_one_liners: 'false',
  nl_before_func_class_def: '0',
  pp_indent_at_level: 'false',
  nl_after_vbrace_open_empty: 'false',
  nl_end_of_file_min: '0',
  pp_region_indent_code: 'false',
  indent_func_proto_param: 'false',
  sp_after_dc: 'ignore',
  indent_brace: '0',
  align_same_func_call_params: 'false',
  sp_bool: 'ignore',
  sp_inside_fparen: 'ignore',
  mod_case_brace: 'ignore',
  nl_before_c_comment: '0',
  sp_before_byref: 'ignore',
  string_escape_char: '92',
  nl_multi_line_define: 'false',
  sp_compare: 'ignore',
  indent_func_ctor_var_param: 'false',
  use_indent_func_call_param: 'true',
  sp_throw_paren: 'ignore',
  sp_after_semi: 'add',
  sp_before_send_oc_colon: 'ignore',
  cmt_c_nl_end: 'false',
  utf8_bom: 'ignore',
  sp_cmt_cpp_start: 'ignore',
  nl_func_decl_args: 'ignore',
  indent_func_param_double: 'false',
  sp_after_ptr_star: 'ignore',
  nl_squeeze_ifdef_top_level: 'false',
  sp_after_mdatype_commas: 'ignore',
  align_on_tabstop: 'false',
  indent_access_spec_body: 'false',
  align_typedef_span: '0',
  sp_before_mdatype_commas: 'ignore',
  align_right_cmt_at_col: '0',
  align_typedef_amp_style: '0',
  sp_before_squares: 'ignore',
  sp_after_cast: 'ignore',
  sp_after_ptr_star_func: 'ignore',
  sp_inside_braces_empty: 'ignore',
  indent_label: '1',
  indent_case_shift: '0',
  indent_sing_line_comments: '0',
  indent_braces_no_class: 'false',
  indent_var_def_cont: 'false',
  sp_inside_tparen: 'ignore',
  sp_scope_paren: 'ignore',
  indent_paren_close: '0',
  nl_class_leave_one_liners: 'false',
  sp_after_oc_at_sel_parens: 'ignore',
  nl_before_block_comment: '0',
  newlines: 'auto',
  pp_define_at_level: 'false',
  sp_after_tparen_close: 'ignore',
  sp_after_oc_scope: 'ignore',
  nl_func_def_end_single: 'ignore',
  indent_oc_block_msg_xcode_style: 'false',
  sp_paren_brace: 'ignore',
  pp_space: 'ignore',
  align_var_struct_gap: '0',
  sp_cond_question_after: 'ignore',
  indent_continue: '0',
  output_tab_size: '8',
  align_func_params: 'false',
  nl_before_return: 'false',
  sp_angle_word: 'ignore',
  sp_before_tr_emb_cmt: 'ignore',
  string_replace_tab_chars: 'false',
  indent_preserve_sql: 'false',
  indent_ctor_init_leading: '2',
  nl_func_proto_type_name: 'ignore',
  sp_inside_braces: 'ignore',
  nl_before_case: 'false',
  nl_enum_identifier_colon: 'ignore',
  sp_before_semi: 'remove',
  mod_remove_empty_return: 'false',
  sp_permit_cpp11_shift: 'false',
  nl_between_annotation: 'ignore',
  nl_before_func_body_def: '0',
  nl_func_type_name: 'ignore',
  sp_func_call_user_inside_fparen: 'ignore',
  nl_func_def_start: 'ignore',
  align_right_cmt_mix: 'false',
  nl_func_leave_one_liners: 'false',
  nl_constr_init_args: 'ignore',
  indent_ternary_operator: '0',
  pp_indent: 'ignore',
  align_var_def_colon: 'false',
  mod_full_brace_if_chain: 'false',
  indent_oc_block_msg_from_caret: 'false',
  mod_full_brace_for: 'ignore',
  indent_min_vbrace_open: '0',
  sp_type_func: 'ignore',
  sp_inside_braces_oc_dict: 'ignore',
  sp_angle_shift: 'add',
  align_pp_define_span: '0',
  align_pp_define_gap: '0',
  nl_before_if: 'ignore',
  nl_after_class: '0',
  indent_member: '0',
  sp_after_semi_for: 'force',
  pos_comma: 'ignore',
  sp_func_def_paren_empty: 'ignore',
  eat_blanks_after_open_brace: 'false',
  nl_remove_extra_newlines: '0',
  align_single_line_brace: 'false',
  indent_xml_string: '0',
  align_left_shift: 'true',
  sp_annotation_paren: 'ignore',
  sp_range: 'ignore',
  sp_member: 'remove',
  nl_paren_dbrace_open: 'ignore',
  sp_inside_newop_paren_close: 'ignore',
  pos_conditional: 'ignore',
  sp_before_oc_colon: 'ignore',
  sp_inside_newop_paren: 'ignore',
  indent_cpp_lambda_only_once: 'false',
  indent_access_spec: '1',
  indent_align_assign: 'true',
  sp_word_brace_ns: 'add',
  indent_oc_msg_prioritize_first_colon: 'true',
  align_oc_msg_colon_first: 'false',
  sp_balance_nested_parens: 'false',
  align_typedef_func: '0',
  nl_switch_brace: 'ignore',
  input_tab_size: '8',
  align_nl_cont: 'false',
  nl_oc_block_brace: 'ignore',
  sp_cmt_cpp_doxygen: 'false',
  nl_after_func_class_proto_group: '0',
  nl_split_while_one_liner: 'false',
  sp_inside_paren_cast: 'ignore',
  sp_after_oc_property: 'ignore',
  sp_inside_oc_at_sel_parens: 'ignore',
  enable_digraphs: 'false',
  indent_func_call_param: 'false',
  sp_word_brace: 'add',
  mod_paren_on_return: 'ignore',
  mod_remove_extra_semicolon: 'false',
  align_var_def_thresh: '0',
  indent_member_single: 'false',
  align_var_def_colon_gap: '0',
  sp_before_unnamed_byref: 'ignore',
  cmt_sp_after_star_cont: '0',
  nl_class_brace: 'ignore',
  nl_func_call_args_multi_line: 'false',
  sp_incdec: 'remove',
  nl_func_def_paren_empty: 'ignore',
  mod_add_long_switch_closebrace_comment: '0',
  align_asm_colon: 'false',
  cmt_cpp_group: 'false',
  sp_addr: 'remove',
  pp_indent_extern: 'true',
  sp_inside_sparen_close: 'ignore',
  sp_pp_concat: 'add',
  sp_after_oc_at_sel: 'ignore',
  align_func_params_gap: '0',
  nl_while_brace: 'ignore',
  nl_create_func_def_one_liner: 'false',
  nl_assign_square: 'ignore',
  nl_using_brace: 'ignore',
  indent_class: 'false',
  align_typedef_gap: '0',
  sp_before_dc: 'ignore',
  cmt_multi_first_len_minimum: '4',
  nl_create_if_one_liner: 'false',
  sp_func_call_paren_empty: 'ignore',
  sp_before_template_paren: 'ignore',
  sp_before_semi_for_empty: 'ignore',
  nl_after_switch: 'ignore',
  nl_max_blank_in_func: '0',
  sp_before_assign: 'ignore',
  align_single_line_func: 'false',
  nl_oc_msg_args: 'false',
  indent_square_nl: 'false',
  sp_cpp_lambda_paren: 'ignore',
  sp_after_oc_synchronized: 'ignore',
  indent_switch_pp: 'true',
  nl_var_def_blk_in: '0',
  indent_constr_colon: 'false',
  mod_sort_oc_property_reference_weight: '0',
  sp_inside_braces_struct: 'ignore',
  sp_fparen_brace_initializer: 'ignore',
  align_var_def_inline: 'false',
  sp_after_type_brace_init_lst_open: 'ignore',
  nl_before_synchronized: 'ignore',
  nl_assign_leave_one_liners: 'false',
  utf8_byte: 'false',
  pos_enum_comma: 'ignore',
  ls_func_split_full: 'false',
  nl_func_call_paren: 'ignore',
  sp_after_send_oc_colon: 'ignore',
  nl_type_brace_init_lst_open: 'ignore',
  indent_single_newlines: 'false',
  sp_after_new: 'ignore',
  nl_func_call_end_multi_line: 'false',
  mod_sort_oc_property_class_weight: '0',
  nl_class_colon: 'ignore',
  align_func_proto_gap: '0',
  nl_func_def_start_multi_line: 'false',
  cmt_multi_check_last: 'true',
  indent_cs_delegate_body: 'false',
  sp_oc_brace_catch: 'ignore',
  nl_brace_catch: 'ignore',
  nl_after_struct: '0',
  mod_sort_using: 'false',
  pp_ignore_define_body: 'false',
  nl_start_of_file_min: '0',
  sp_func_call_paren: 'ignore',
  sp_before_semi_for: 'ignore',
  nl_while_leave_one_liners: 'false',
  nl_after_return: 'false',
  nl_oc_brace_catch: 'ignore',
  sp_brace_catch: 'ignore',
  indent_col1_comment: 'false',
  align_assign_span: '0',
  cmt_insert_before_preproc: 'false',
  sp_before_comma: 'remove',
  indent_func_def_force_col1: 'false',
  nl_func_def_end: 'ignore',
  align_func_params_span: '0',
  nl_after_while: 'ignore',
  code_width: '0',
  indent_ctor_init: '0',
  nl_func_paren: 'ignore',
  sp_before_pp_stringify: 'ignore',
  mod_full_brace_if: 'ignore',
  sp_before_oc_dict_colon: 'ignore',
  nl_func_decl_end_multi_line: 'false',
  mod_add_long_ifdef_endif_comment: '0',
  indent_with_tabs: '1',
  indent_braces_no_struct: 'false',
  indent_first_for_expr: 'false',
  cmt_insert_before_inlines: 'true',
  sp_after_invariant_paren: 'ignore',
  indent_func_throw: '0',
  mod_full_brace_if_chain_only: 'false',
  indent_paren_after_func_call: 'false',
  mod_add_long_namespace_closebrace_comment: '0',
  mod_sort_oc_property_thread_safe_weight: '0',
  nl_after_vbrace_close: 'false',
  nl_func_call_paren_empty: 'ignore',
  nl_if_leave_one_liners: 'false',
  sp_sparen_brace: 'ignore',
  nl_func_def_args: 'ignore',
  nl_func_def_start_single: 'ignore',
  sp_after_oc_type: 'ignore',
  nl_namespace_two_to_one_liner: 'false',
  sp_not: 'remove',
  indent_func_const: '0',
  tok_split_gte: 'false',
  nl_brace_while: 'ignore',
  nl_func_def_empty: 'ignore',
  use_indent_continue_only_once: 'false',
  nl_before_while: 'ignore',
  sp_func_proto_paren: 'ignore',
  nl_func_def_paren: 'ignore',
  indent_oc_block_msg_from_keyword: 'false',
  sp_before_sparen: 'ignore',
  nl_synchronized_brace: 'ignore',
  sp_brace_else: 'ignore',
  align_on_operator: 'false',
  sp_after_type: 'force',
  nl_enum_own_lines: 'ignore',
  indent_else_if: 'false',
  nl_func_type_name_class: 'ignore',
  nl_typedef_blk_end: '0',
  indent_paren_after_func_def: 'false',
  nl_cpp_ldef_brace: 'ignore',
  nl_oc_msg_leave_one_liner: 'false',
  align_var_struct_thresh: '0',
  nl_create_while_one_liner: 'false',
  nl_after_brace_open_cmt: 'false',
  sp_special_semi: 'ignore',
  sp_inv: 'remove',
  ls_for_split_full: 'false',
  pp_indent_case: 'true',
  mod_pawn_semicolon: 'false',
  sp_inside_paren: 'ignore',
  indent_namespace_single_indent: 'false',
  nl_func_decl_start_single: 'ignore',
  sp_after_operator_sym: 'ignore',
  nl_elseif_brace: 'ignore',
  nl_tsquare_brace: 'ignore',
  sp_num_before_tr_emb_cmt: '0',
  pos_constr_comma: 'ignore',
  sp_after_angle: 'ignore',
  nl_after_func_body: '0',
  mod_sort_include: 'false',
  align_func_proto_span: '0',
  use_options_overriding_for_qt_macros: 'true',
  pos_class_colon: 'ignore',
  sp_after_class_colon: 'ignore',
  indent_relative_single_line_comments: 'false',
  align_struct_init_span: '0',
  sp_inside_angle: 'ignore',
  sp_after_sparen: 'ignore',
  nl_assign_brace: 'ignore',
  cmt_c_group: 'false',
  indent_oc_block_msg: '0',
  indent_bool_paren: 'false',
  nl_split_if_one_liner: 'false',
  indent_off_after_return_new: 'false',
  sp_func_def_paren: 'ignore',
  sp_after_semi_for_empty: 'ignore',
  cmt_star_cont: 'false',
  force_tab_after_define: 'false',
  nl_before_func_body_proto: '0',
  nl_brace_else: 'ignore',
  sp_cond_colon_before: 'ignore',
  mod_full_brace_nl: '0',
  sp_inside_braces_enum: 'ignore',
  nl_func_def_end_multi_line: 'false',
  nl_func_var_def_blk: '0',
  sp_assign_default: 'ignore',
  sp_after_for_colon: 'ignore',
  align_mix_var_proto: 'false',
  nl_before_class: '0',
  nl_create_for_one_liner: 'false',
  sp_defined_paren: 'ignore',
  sp_cmt_cpp_qttr: 'false',
  sp_after_oc_block_caret: 'ignore',
  nl_typedef_blk_start: '0',
  sp_try_brace: 'ignore',
  nl_brace_struct_var: 'ignore',
  indent_case_brace: '0',
  indent_using_block: 'true',
  nl_after_func_body_one_liner: '0',
  pp_indent_brace: 'true',
  mod_sort_oc_property_getter_weight: '0',
  sp_after_byref_func: 'ignore',
  nl_union_brace: 'ignore',
  sp_func_class_paren_empty: 'ignore',
  align_pp_define_together: 'false',
  string_escape_char2: '0',
  nl_cs_property_leave_one_liners: 'false',
  sp_before_unnamed_ptr_star: 'ignore',
  nl_cpp_lambda_leave_one_liners: 'false',
  indent_class_on_colon: 'false',
  sp_enum_paren: 'ignore',
  nl_after_brace_open: 'false',
  sp_after_assign: 'ignore',
  sp_cond_ternary_short: 'ignore',
  sp_cpp_lambda_assign: 'ignore',
  nl_multi_line_cond: 'false',
  nl_squeeze_ifdef: 'false',
  sp_getset_brace: 'ignore',
  align_var_def_gap: '0',
  pos_arith: 'ignore',
  nl_around_cs_property: '0',
  sp_super_paren: 'remove',
  sp_func_proto_paren_empty: 'ignore',
  nl_func_decl_args_multi_line: 'false',
  cmt_cpp_to_c: 'false',
  nl_before_access_spec: '0',
  align_keep_extra_space: 'false',
  sp_angle_paren_empty: 'ignore',
  sp_skip_vbrace_tokens: 'false',
  align_number_right: 'false',
  sp_inside_newop_paren_open: 'ignore',
  nl_before_if_closing_paren: 'ignore',
  indent_cpp_lambda_body: 'false',
  sp_inside_square_oc_array: 'ignore',
  nl_struct_brace: 'ignore',
  sp_cpp_before_struct_binding: 'ignore',
  nl_after_do: 'ignore',
  sp_before_ellipsis: 'ignore',
  align_enum_equ_thresh: '0',
  cmt_cpp_nl_end: 'false',
  sp_inside_square: 'ignore',
  indent_paren_after_func_decl: 'false',
  cmt_indent_multi: 'true',
  sp_after_ptr_star_qualifier: 'ignore',
  nl_if_brace: 'ignore',
  ls_code_width: 'false',
  indent_switch_case: '0',
  sp_func_call_user_paren: 'ignore',
  nl_getset_brace: 'ignore',
  sp_after_comma: 'ignore',
  nl_define_macro: 'false',
  sp_case_label: 'ignore',
  sp_version_paren: 'ignore',
  nl_func_decl_start_multi_line: 'false',
  indent_single_after_return: 'false',
  indent_align_paren: 'true',
  mod_full_brace_do: 'ignore',
  nl_constr_colon: 'ignore',
  nl_fdef_brace: 'ignore',
  nl_before_do: 'ignore',
  nl_brace_brace: 'ignore',
  sp_attribute_paren: 'ignore',
  indent_columns: '8',
  sp_cpp_cast_paren: 'ignore',
  nl_try_brace: 'ignore',
  nl_ds_struct_enum_cmt: 'false',
  nl_do_brace: 'ignore',
  sp_arith: 'ignore',
  nl_after_case: 'false',
  indent_ignore_asm_block: 'false',
  nl_after_synchronized: 'ignore',
  sp_after_byref: 'ignore',
  nl_brace_fparen: 'ignore',
  align_oc_decl_colon: 'false',
  sp_after_constr_colon: 'ignore',
  sp_enum_before_assign: 'ignore',
  sp_inside_type_brace_init_lst: 'ignore',
  align_var_def_star_style: '0',
  nl_var_def_blk_start: '0',
  sp_before_square: 'ignore',
  sp_angle_colon: 'ignore',
  eat_blanks_before_close_brace: 'false',
  sp_macro: 'ignore',
  align_with_tabs: 'false',
  mod_sort_oc_properties: 'false',
  sp_return_paren: 'ignore',
  sp_d_array_colon: 'ignore',
  nl_type_brace_init_lst_close: 'ignore',
  sp_after_operator: 'ignore',
  sp_this_paren: 'remove',
  cmt_c_nl_start: 'false',
  nl_after_multiline_comment: 'false',
  sp_inside_sparen_open: 'ignore',
  pp_indent_func_def: 'true',
  pp_indent_region: '0',
  sp_template_angle: 'ignore',
  nl_property_brace: 'ignore',
  align_var_struct_span: '0',
  mod_full_paren_if_bool: 'false',
  nl_func_call_start_multi_line: 'false',
  pp_if_indent_code: 'false',
  sp_cond_colon: 'ignore',
  pos_assign: 'ignore',
  sp_brace_finally: 'ignore',
  nl_split_for_one_liner: 'false',
  sp_after_ptr_block_caret: 'ignore',
  sp_before_byref_func: 'ignore',
  indent_first_bool_expr: 'false',
  align_keep_tabs: 'false',
  sp_after_oc_return_type: 'ignore',
  mod_sort_oc_property_nullability_weight: '0',
  nl_brace_finally: 'ignore',
  sp_angle_paren: 'ignore',
  nl_after_func_proto: '0',
  sp_after_throw: 'ignore',
  sp_brace_typedef: 'ignore',
  pos_compare: 'ignore',
  sp_macro_func: 'ignore',
  sp_paren_comma: 'force',
  nl_after_try_catch_finally: '0',
  nl_func_paren_empty: 'ignore',
  sp_after_operator_sym_empty: 'ignore',
  nl_enum_class_identifier: 'ignore',
  nl_after_annotation: 'ignore',
  indent_func_class_param: 'false',
  sp_cond_question: 'ignore',
  sp_catch_paren: 'ignore',
  pos_constr_colon: 'ignore',
  mod_full_brace_function: 'ignore',
  align_enum_equ_span: '0',
  nl_after_brace_close: 'false',
  nl_brace_square: 'ignore',
  nl_before_for: 'ignore',
  nl_after_vbrace_open: 'false',
  sp_func_class_paren: 'ignore',
  align_single_line_brace_gap: '0',
  mod_full_brace_nl_block_rem_mlcond: 'false',
  sp_cparen_oparen: 'ignore',
  indent_extern: 'false',
  mod_add_long_class_closebrace_comment: '0',
  sp_deref: 'remove',
  sp_before_ptr_star: 'ignore',
  sp_enum_colon: 'ignore',
  indent_namespace_limit: '0',
  nl_after_label_colon: 'false',
  nl_else_if: 'ignore',
  sp_enum_after_assign: 'ignore',
  sp_ptr_star_paren: 'ignore',
  nl_enum_colon_type: 'ignore',
  align_var_def_attribute: 'false',
  nl_else_brace: 'ignore',
  sp_pp_stringify: 'ignore',
  sp_before_angle: 'ignore',
  sp_after_newop_paren: 'ignore',
  indent_vbrace_open_on_tabstop: 'false',
  nl_catch_brace: 'ignore',
  nl_enum_brace: 'ignore',
  mod_sort_oc_property_readwrite_weight: '0',
  pp_indent_count: '1',
  sp_enum_assign: 'ignore',
  align_oc_msg_colon_span: '0',
  indent_brace_parent: 'false',
  mod_sort_oc_property_setter_weight: '0',
  nl_finally_brace: 'ignore',
  nl_before_switch: 'ignore',
  indent_template_param: 'false',
  sp_square_fparen: 'ignore',
  nl_fcall_brace: 'ignore',
  align_var_def_amp_style: '0',
  nl_var_def_blk_end: '0',
  sp_before_nl_cont: 'add',
  nl_comment_func_def: '0',
  align_var_def_span: '0',
  sp_before_case_colon: 'remove',
  sp_after_tag: 'ignore',
  sp_after_oc_dict_colon: 'ignore',
  nl_before_func_class_proto: '0',
  indent_class_colon: 'false',
  nl_max: '0',
  sp_before_oc_block_caret: 'ignore',
  sp_invariant_paren: 'ignore',
  indent_braces: 'false',
  pp_indent_if: '0',
  nl_func_class_scope: 'ignore',
  mod_move_case_break: 'false',
  nl_after_func_body_class: '0',
  cmt_insert_before_ctor_dtor: 'false',
  sp_inside_fparens: 'ignore',
  nl_before_throw: 'ignore',
  nl_collapse_empty_body: 'false',
  sp_between_new_paren: 'ignore',
  sp_cond_question_before: 'ignore',
  pos_bool: 'ignore',
  sp_inside_sparen: 'ignore',
  sp_finally_brace: 'ignore',
  indent_paren_open_brace: 'false',
  indent_paren_nl: 'false',
  cmt_convert_tab_to_spaces: 'false',
  sp_sizeof_paren: 'ignore',
  nl_between_get_set: '0',
  indent_oc_block_msg_from_colon: 'false',
  indent_namespace: 'false',
  sp_fparen_dbrace: 'ignore',
  sp_between_ptr_star: 'ignore',
  indent_param: '0',
  nl_after_func_class_proto: '0',
  sp_cond_colon_after: 'ignore',
  indent_semicolon_for_paren: 'false',
  indent_var_def_blk: '0',
  nl_func_decl_end_single: 'ignore',
  indent_comma_paren: 'false',
  sp_else_brace: 'ignore',
  warn_level_tabs_found_in_verbatim_string_literals: '2',
  nl_return_expr: 'ignore',
  indent_shift: 'false',
  mod_add_long_function_closebrace_comment: '0',
  sp_before_constr_colon: 'ignore',
  mod_full_brace_while: 'ignore',
  nl_start_of_file: 'ignore',
  nl_after_access_spec: '0',
  indent_func_def_param: 'false',
  sp_oc_catch_paren: 'ignore',
  sp_catch_brace: 'ignore',
  sp_between_mdatype_commas: 'ignore',
  nl_func_call_empty: 'ignore',
  cmt_reflow_mode: '0',
  nl_enum_leave_one_liners: 'false',
  nl_end_of_file: 'ignore',
  mod_add_long_ifdef_else_comment: '0',
};
