export const ClangFormatTemplate = {
  AccessModifierOffset: [null, -4, -3, -2, -1, 0, 1, 2, 3, 4],
  AlignAfterOpenBracket: [null, 'Align', 'DontAlign', 'AlwaysBreak'],
  AlignConsecutiveAssignments: [null, true, false],
  AlignConsecutiveDeclarations: [null, true, false],
  AlignEscapedNewlines: [null, 'Right', 'Left', 'DontAlign'],
  AlignOperands: [null, true, false],
  AlignTrailingComments: [null, true, false],
  AllowAllParametersOfDeclarationOnNextLine: [null, true, false],
  AllowShortBlocksOnASingleLine: [null, true, false],
  AllowShortCaseLabelsOnASingleLine: [null, true, false],
  AllowShortFunctionsOnASingleLine: [
    null,
    'All',
    'Inline',
    'Empty',
    'InlineOnly',
    'None',
  ],
  AllowShortIfStatementsOnASingleLine: [null, true, false],
  AllowShortLoopsOnASingleLine: [null, true, false],
  AlwaysBreakAfterDefinitionReturnType: [
    null,
    'None',
    'All',
    'TopLevel',
  ],
  AlwaysBreakAfterReturnType: [
    null,
    'None',
    'All',
    'TopLevel',
    'AllDefinitions',
    'TopLevelDefinitions',
  ],
  AlwaysBreakBeforeMultilineStrings: [null, true, false],
  AlwaysBreakTemplateDeclarations: [null, true, false],
  BinPackArguments: [null, true, false],
  BinPackParameters: [null, true, false],
  BraceWrapping: {
    AfterClass: [null, true, false],
    AfterControlStatement: [null, true, false],
    AfterEnum: [null, true, false],
    AfterFunction: [null, true, false],
    AfterNamespace: [null, true, false],
    AfterObjCDeclaration: [null, true, false],
    AfterStruct: [null, true, false],
    AfterUnion: [null, true, false],
    AfterExternBlock: [null, true, false],
    BeforeCatch: [null, true, false],
    BeforeElse: [null, true, false],
    IndentBraces: [null, true, false],
    SplitEmptyFunction: [null, true, false],
    SplitEmptyRecord: [null, true, false],
    SplitEmptyNamespace: [null, true, false],
  },
  BreakBeforeBinaryOperators: [null, 'None', 'NonAssignment', 'All'],
  BreakBeforeBraces: [
    null,
    'Attach',
    'Linux',
    'Mozilla',
    'Stroustrup',
    'Allman',
    'GNU',
    'WebKit',
    'Custom',
  ],
  BreakBeforeInheritanceComma: [null, true, false],
  BreakBeforeTernaryOperators: [null, true, false],
  BreakConstructorInitializersBeforeComma: [null, true, false],
  BreakConstructorInitializers: [
    null,
    'BeforeColon',
    'BeforeComma',
    'AfterColon',
  ],
  BreakAfterJavaFieldAnnotations: [null, true, false],
  BreakStringLiterals: [null, true, false],
  ColumnLimit: [null, 70, 72, 74, 76, 78, 80, 84, 88, 89, 90, 98],
  CompactNamespaces: [null, true, false],
  ConstructorInitializerAllOnOneLineOrOnePerLine: [null, true, false],
  ConstructorInitializerIndentWidth: [
    null,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
  ],
  ContinuationIndentWidth: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  Cpp11BracedListStyle: [null, true, false],
  DerivePointerAlignment: [null, true, false],
  ExperimentalAutoDetectBinPacking: [null, true, false],
  FixNamespaceComments: [null, true, false],
  IncludeBlocks: [null, 'Preserve', 'Merge', 'Regroup'],
  IndentCaseLabels: [null, true, false],
  IndentPPDirectives: [null, 'None', 'AfterHash'],
  IndentWidth: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  IndentWrappedFunctionNames: [null, true, false],
  JavaScriptQuotes: [null, 'Single', 'Double', 'Leave'],
  JavaScriptWrapImports: [null, true, false],
  KeepEmptyLinesAtTheStartOfBlocks: [null, true, false],
  MaxEmptyLinesToKeep: [null, 0, 1, 2, 3, 4],
  NamespaceIndentation: [null, 'None', 'Inner', 'All'],
  ObjCBlockIndentWidth: [null, 0, 1, 2, 3, 4],
  ObjCSpaceAfterProperty: [null, true, false],
  ObjCSpaceBeforeProtocolList: [null, true, false],
  PointerAlignment: [null, 'Left', 'Middle', 'Right'],
  ReflowComments: [null, true, false],
  SortIncludes: [null, true, false],
  SortUsingDeclarations: [null, true, false],
  SpaceAfterCStyleCast: [null, true, false],
  SpaceAfterTemplateKeyword: [null, true, false],
  SpaceBeforeAssignmentOperators: [null, true, false],
  SpaceBeforeParens: [null, 'Never', 'ControlStatements', 'Always'],
  SpaceInEmptyParentheses: [null, true, false],
  SpacesBeforeTrailingComments: [null, 0, 1, 2, 3, 4, 5, 6, 7, 8],
  SpacesInAngles: [null, true, false],
  SpacesInContainerLiterals: [null, true, false],
  SpacesInCStyleCastParentheses: [null, true, false],
  SpacesInParentheses: [null, true, false],
  SpacesInSquareBrackets: [null, true, false],
  Standard: [null, 'Cpp11', 'Cpp03', 'Auto'],
  TabWidth: [null, 2, 4, 8],
  UseTab: [
    null,
    'ForIndentation',
    'ForContinuationAndIndentation',
    'Always',
    'Never',
  ],
};
